### ISSUE TITLE
Freeze SOLikeT MFLike to v0.7 from LAT_MFLike

### ISSUE THREAD

**Issue by itrharrison** [simonsobs/SOLikeT#90]
MFLike here and on https://github.com/simonsobs/LAT_MFLike have diverged. Given the continued development of MFLike there, it seems most sensible to freeze the version of MFLike used for the SOLikeT v0.1 to be a stable version, the most recent of which is v0.7.

**Comment by itrharrison** [comment]
As per discussion with @reneehlozek this needs to be made clear in documentation too!

**Comment by sgiardie** [comment]
Maybe it's better to freeze to the most recent MFLike version, since there was a [bug in the bandpass integration when using bandpass shifts](https://github.com/simonsobs/LAT_MFLike/pull/58), which would still be present in v0.7. 
This bug is now present in [`soliket/bandpass.py`](https://github.com/simonsobs/SOLikeT/blob/e390ed1e313e113155b866888eff3f79c6aac3e1/soliket/bandpass.py#L144) and not directly in `soliket/mflike`, so the two things can also be solved separately. But it seems more linear to me to adapt everything to the most recent version... what do you think?

**Comment by itrharrison** [comment]
Is the most recent version v0.8? How much work would it be to move from the current version to that? What would be the timescale you think you could do it on?

**Comment by sgiardie** [comment]
The most recent one, which is also the one fixing this bug, is the v0.8.3. 
About the work: not too little, there is work to be done in mflike.py, theoryforge.py, bandpass.py (not sure about foreground.py).  In MFLike we removed some outdated bandpass functions, but in soliket/bandpass.py we may be interested in keeping more options. In general the most relevant upgrade in v0.8 vs v0.7 was moving from using `frequencies` to using the combination `experiment_frequency`, which is much more useful when combining different arrays from the same experiment or more experiments. The question is also if we consider this upgrade important to be ported now in soliket
About timescale: I may need some time to do that (and especially to find time to work on that)... I can foresee a timescale of few months
